config/routes.rb
Rails.application.routes.draw do

  get 'leader_boards/index'

  get('/', { to: 'welcome#about', as: 'home' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


  resources :drills do
     member do
       get :delete
     end
   end

resources :drills do
  resources :answers
end

resources :attempted_drills


 resources :drill_groups do
   member do
     get :delete
   end
 end

 resources :leader_boards, only: :index
 resources :my_drills, only: [:index, :destroy] do
   member do
     get :delete
   end
 end

end

app/models/drill_group.rb
class DrillGroup < ApplicationRecord
end

app/controllers/drill_groups_controller.rb
class DrillGroupsController < ApplicationController
  def index
    @drill_groups = DrillGroup.order("id")
  end

  def show
    # if redirect from new drill create =>
    #  if Drill.find_by(id: params[:id]) != nil
    #    @drill_group = Drill.find(params[:id]).drill_group
    #  else
    #    @drill_group = DrillGroup.find_by(id: params[:id])
    #  end
    @drill_group = DrillGroup.find_by(id: params[:id])
    @drills = @drill_group.drills

   end

  def new
    @drill_group = DrillGroup.new
  end

  def create
    @drill_group = DrillGroup.new(drill_group_params)

    if @drill_group.save
      flash[:notice] = "Drill Group created successfully"
      redirect_to(drill_groups_path)
    else
      flash[:error] = "Drill was not created"
      render("new")
    end
  end

  def edit
    @drill_group = DrillGroup.find(params[:id])
  end

  def update
    @drill_group = DrillGroup.find(params[:id])
    if @drill_group.update_attributes(drill_group_params)
      flash[:notice] = "Drill Group Updated"
      redirect_to(drill_groups_path)
    else
      render("edit")
    end
  end

  def delete
    @drill_group = DrillGroup.find(params[:id])
  end

  def destroy
    @drill_group = DrillGroup.find(params[:id])
    @drill_group.destroy

    flash[:notice] = "Drill Group destroyed!"
    redirect_to(drill_groups_path)
  end

  private
  def drill_group_params
    params.require(:drill_group).permit(:id,:drill_group_name, :difficulty)
  end



end

app/views/drill_groups/delete.html.erb
<%= link_to("Back to list", drill_groups_path, :class => 'waves-effect waves-light btn')%>
<div class="delete drill-groups">
  <h2>Delete Drill</h2>
  <%= form_for(@drill_group, :method => 'DELETE') do |f| %>
    <p>Are you sure you want to permanently delete this drill?</p>
    <div class="form-buttons">
      <%= f.submit("Delete  Drill",class:'waves-effect delete-button waves-light btn') %>
    </div>
  <% end %>
</div>

app/views/drill_groups/edit.html.erb
<div class="new drill_groups">
  <h2>Edit Drill Groups</h2>
  <div class="form-buttons">
    <%= link_to("  Back to Drill Groups List", drill_groups_path, :class => "waves-effect  waves-light btn") %>
  </div>
  <%= form_for(@drill_group) do |f| %>
    <table>
      <tr>
        <th>Drill Group Title</th>
        <td><%= f.text_field(:drill_group_name) %></td>
      </tr>
      <tr>
        <th>Difficulty</th>
        <td>
          <%= f.check_box :difficulty, style:"opacity:1; pointer-events: auto; display: none !important;", id:"Easy", class:"checkbox"%>
          <%= f.label "Beginner", for:"Easy" %>

          <%= f.check_box :difficulty, style:"opacity:1; pointer-events: auto; display: none !important;", id:"normal",class:"checkbox"%>
          <%= f.label "Advanced", for:"normal" %>
        </td>
      </tr>
    </table>
    <div class="form-buttons">
      <%= f.submit("Update Drill Group", class:"waves-effect edit-button waves-light btn") %>
    </div>
  <% end %>
</div>

app/views/drill_groups/index.html.erb
<div class="drill_groups">
  <% if current_user != nil %>
    <% if current_user.is_admin? %>
      <%= link_to("Add New Drill Group", new_drill_group_path, :class => "waves-effect waves-light margins btn right button-margin z-depth-3") %>
    <% end %>
  <% end %>
  <div class="row">
    <% @drill_groups.each do |drill_group| %>
        <div class="cards col s12 z-depth-3">
          <div class="col s6">
            <h4><%= link_to(drill_group.drill_group_name,  drill_group_path(drill_group), class: "teal-text") %></h4>
            <% if (drill_group.difficulty == "0") %>
              <h6>Beginner</h6>
              <% else %>
              <h6>Advanced</h6>
            <% end %>
          </div>

          <div class="col s6 right flex-end">
            <% if current_user != nil %>
              <% if current_user.is_admin? %>
                <%= link_to("Edit", edit_drill_group_path(drill_group), :class => "waves-effect edit-button waves-light btn white teal-text") %>
                <%= link_to("Delete", delete_drill_group_path(drill_group), :class => "waves-effect delete-button waves-light btn btn1 white red-text") %>
              <% end %>
            <% end %>
          </div>

        </div>
    <% end %>
  </div>

  <% if current_user != nil %>
    <% if current_user.is_admin? %>
      <%= link_to("Add New Drill Group", new_drill_group_path, :class => "waves-effect waves-light margins btn right button-margin z-depth-3") %>
    <% end %>
  <% end %>
</div>

app/views/drill_groups/new.html.erb
<div class="new drill_groups">
  <h2>Create Drill Groups</h2>
  <%= form_for(@drill_group) do |f| %>
    <table>
      <tr>
        <th>Drill Group Title</th>
        <td>
          <%= f.text_field(:drill_group_name) %></td>
      </tr>
      <tr>
        <th>Difficulty</th>
        <td>

          <%= f.check_box :difficulty, style:"opacity:1; pointer-events: auto; display: none !important;", id:"Easy", class:"checkbox",value:'easy' %>
          <%= f.label "Beginner", for:"Easy" %>

          <%= f.check_box :difficulty, style:"opacity:1; pointer-events: auto; display: none !important;", id:"normal",class:"checkbox"%>
          <%= f.label "Advanced", for:"normal" %>


        </td>
      </tr>
    </table>
    <div class="form-buttons">
      <%= f.submit("Create Drill Group",class:'waves-effect waves-light btn') %>
      <%= link_to("Back to Drill Groups List", drill_groups_path, :class => "waves-effect waves-light btn") %>
    </div>
  <% end %>
</div>

app/views/drill_groups/show.html.erb
<div class="index drills">


  <h1><%= @drill_group.drill_group_name %></h1>
  <div class="row">
    <%= link_to "Back to Drill Group", drill_groups_path, class:'waves-effect waves-light btn left'%>
    <% if current_user != nil %>
      <% if current_user.is_admin? %>
        <%= link_to("Add a new Drill", "/drills/new?groupsId=#{@drill_group.id}",class: 'waves-effect waves-light btn right')  %>
      <% end %>
    <% end %>
  </div>

  <% @drills.each do |d| %>
  <div class="row">
    <div class="cards col s12 z-depth-3">
      <div class="col s6">
        <div class="drill-link">
          <h6><%= link_to(d.title,  drill_path(d)) %></h6>
        </div>
        <div class="points">
          <%= d.points %> Points
        </div>
      </div>
      <div class="col s6 right flex-end">
        <% if current_user != nil %>
          <% if current_user.is_admin? %>
            <%= link_to("Edit", edit_drill_path(d), :class => "waves-effect edit-button waves-light btn white teal-text") %>
            <%= link_to("Delete", delete_drill_path(d), :class => "waves-effect delete-button waves-light btn btn1 white red-text") %>
          <%end%>
        <%end%>
      </div>


    </div>
  </div>
  <%end%>

  <div class="margins">
    <%= link_to "Back to Drill Group", drill_groups_path, class:'waves-effect waves-light btn left'%>
    <% if current_user != nil %>
    <% if current_user.is_admin? %>
    <%= link_to("Add a new Drill", "/drills/new?groupsId=#{@drill_group.id}",class: 'waves-effect waves-light btn right')  %>
    <% end %>
    <% end %>
  </div>
</div>