config/routes.rb
Rails.application.routes.draw do

  get 'leader_boards/index'

  get('/', { to: 'welcome#about', as: 'home' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


  resources :drills do
     member do
       get :delete
     end
   end

resources :drills do
  resources :answers
end

resources :attempted_drills


 resources :drill_groups do
   member do
     get :delete
   end
 end

 resources :leader_boards, only: :index
 resources :my_drills, only: [:index, :destroy] do
   member do
     get :delete
   end
 end

end

app/models/drill.rb
class Drill < ApplicationRecord
<<<<<<< HEAD
=======
  belongs_to :drill_group, :optional => true
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers

>>>>>>> a4a7eba20c25759ff95fdea51a308eb41151e36e
end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController

  def index
    @drills = Drill.order("id")
  end

  def show
    if current_user === nil
      redirect_to new_user_path
    end
    @drill = Drill.find(params[:id])
    @answers = @drill.answers
    @attempted_drill = AttemptedDrill.new
    @drill_group = DrillGroup.find_by(id: params[:id])

  end

  def new
    @drill = Drill.new
    @drill.drill_group_id = params[:groupsId]
    4.times { @drill.answers.build}


  end

  def create
    @drill = Drill.new(drill_params)
    if @drill.save
      flash[:notice] = "Drill created successfully"
      redirect_to(drill_group_path(@drill.drill_group))
    else
      flash[:error] = "Drill was not created!"
      render("new")
    end
  end

  def edit
    @drill = Drill.find(params[:id])
  end

  def update
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(drill_params)
      flash[:notice] = "Drill updated successfully"
      redirect_to(drills_path)
    else
      flash[:error] = "Drill was not updated!"
      render("edit")
    end
  end

  def delete
    @drill = Drill.find(params[:id])
  end

  def destroy
    @drill = Drill.find(params[:id])
    @drill.destroy

    flash[:notice] = "Drill destroyed successfully."
    redirect_to(drills_path)
  end

  private

  def drill_params
    params.require(:drill).permit(:title, :points, :drill_group_id, answers_attributes: [:body, :is_correct])
  end


end

app/views/drills/delete.html.erb
<div class="delete drills">
  <h2>Delete Drill</h2>
  <%= form_for(@drill, :method => 'DELETE') do |f| %>
    <p>Are you sure you want to permanently delete this drill?</p>
    <div class="form-buttons">
      <%= f.submit("Delete Drill", class:'waves-effect delete-button  waves-light btn') %>
      <%= link_to("Back to list", drills_path, :class => 'waves-effect waves-light btn')%>
    </div>
  <% end %>
</div>

app/views/drills/edit.html.erb
<%= link_to("Back to Drill list", drills_path, :class => "waves-effect  waves-light btn") %>
<div class="new drills">
  <h2>Edit Drills</h2>


  <%= form_for(@drill) do |f| %>
    <table>
      <tr>
        <th>Drill Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Drill Points</th>
        <td><%= f.text_field(:points) %></td>
      </tr>
      <tr style="display:none;">
        <th>Drill Group</th>
        <td><%= f.text_field(:drill_group_id) %></td>
      </tr>

      <td>
        <div class="form-buttons">
          <%= f.submit("Create Drill", class:'waves-effect  waves-light btn') %>
        </div>
      </td>

      <% end %>

    </table>





</div>

app/views/drills/index.html.erb
<div class="index drills">
  <h2>Drills</h2>
  <%= link_to("Add New Drills", new_drill_path, :class => "waves-effect waves-light btn") %>
  <table class="listing">
    <tr class="header">
      <th>No.</th>
      <th>Title</th>
      <th>Points</th>
    </tr>
    <% counter = 0
    @drills.each do |drill| %>
      <tr>
        <td><%= counter += 1 %></td>
        <td><%= drill.title %></td>
        <td><%= drill.points %></td>
        <td>
          <div class = 'butonIndex'>
          <%= link_to("Edit", edit_drill_path(drill), :class => "waves-effect edit-button waves-light btn") %>
          <%= link_to("Delete", delete_drill_path(drill), :class => "waves-effect delete-button waves-light btn1 btn ") %>
        </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/drills/new.html.erb
<%= link_to("Back to Drill list", drills_path, :class => "waves-effect  waves-light btn") %>
<div class="new drills">
  <h2>Create Drills</h2>


  <%= form_for(@drill) do |f| %>
    <table>
      <tr>
        <th>Drill Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Drill Points</th>
        <td><%= f.text_field(:points) %></td>
      </tr>
      <tr style="display:none;">
        <th>Drill Group</th>
        <td><%= f.text_field(:drill_group_id) %></td>
      </tr>
      <tr>
        <th>Answers</th>

      </tr>

      <%= f.fields_for :answers do |answer| %>
      <tr>
        <th>
          <%= answer.label :body %>
        </th>
        <td>
          <%= answer.text_field :body %>
          <%= answer.check_box :is_correct?, style:"opacity:1; pointer-events: auto; display: none !important;" , class:"checkbox" , id:"checkbox#{answer.index}"%>
          <%= answer.label "Is correct?", for:"checkbox#{answer.index}" %>
        </td>
      </tr>

      <% end %>

      <td>
        <div class="form-buttons">
          <%= f.submit("Create Drill", class:'waves-effect  waves-light btn') %>
        </div>
      </td>

      <% end %>

    </table>





</div>

app/views/drills/show.html.erb
<h3><%=@drill.title%></h3>

<div>

  <%= form_for @attempted_drill do |attempt| %>
    <% @answers.each do |answer|%>
    <div class="AnswersChoice">
      <%= radio_button_tag(:answer, answer.id.to_i) %>
      <%= label_tag( ("answer_" + "#{answer.id}").to_sym, "#{answer.body}") %>
    </div>
    <br>
    <% end %>
    <br>
    <%= attempt.submit "Answer", class:'waves-effect waves-light btn' %>
    <%= link_to "Next Drill", drill_path(@drill.id + 1), class:'waves-effect waves-light btn'%>
    <%= link_to "Drill Group", drill_groups_path(@dril), class:'waves-effect waves-light btn'%>
  <% end %>

  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
  <% end %>