config/routes.rb
Rails.application.routes.draw do

  get 'leader_boards/index'

  get('/', { to: 'welcome#about', as: 'home' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


  resources :drills do
     member do
       get :delete
     end
   end

resources :drills do
  resources :answers
end

resources :attempted_drills


 resources :drill_groups do
   member do
     get :delete
   end
 end

 resources :leader_boards, only: :index
 resources :my_drills, only: [:index, :destroy] do
   member do
     get :delete
   end
 end

end

app/controllers/my_drills_controller.rb
class MyDrillsController < ApplicationController

  def index

    @my_drills = {}
    @drill_groups = []
    my_att_drills = AttemptedDrill.where(user_id: current_user.id)
    my_att_drills.each do |drill|
      current_drill_group = DrillGroup.find_by_id(drill.drill_group_id)
      if !@my_drills.key?(current_drill_group.drill_group_name)
        group_total = my_att_drills.where(drill_group_id: current_drill_group.id)
        correct =  group_total.where(is_correct: true)
        score = (correct.count.to_f/group_total.count).round(2) * 100
        @my_drills[current_drill_group.drill_group_name] = score
        @drill_groups << current_drill_group
      end
    end
  end

  def delete
    @drill_group = DrillGroup.find(params[:id])
  end

  def destroy
    att_drills = AttemptedDrill.where(user_id: current_user.id).where(drill_group_id: params[:id])
    att_drills.destroy_all

    redirect_to(my_drills_path, notice: "Drills deleted!")
  end

end

app/helpers/my_drills_helper.rb
module MyDrillsHelper
end

app/views/my_drills/delete.html.erb
<div class="">
  <h4>Are you sure you want to delete all your drills of <%= @drill_group.drill_group_name %> ?</h4>
  <%= link_to("DELETE", my_drill_path(@drill_group), method: :delete, class: "btn btn-danger") %>
</div>

app/views/my_drills/index.html.erb
<div class="index drills">
  <h2>My Drills</h2>

    <% count = 0 %>
    <% @my_drills.each do |key, value| %>
      <div class="drill_group">
        <h3><%= key %></h3>
        <h5>Score: <%= value %>%</h5>
      </div>
      <%= link_to("Start", drill_group_path(@drill_groups[count])) %>
      <%= link_to("Remove", delete_my_drill_path(@drill_groups[count]))%>
      <% count += 1 %>
    <% end %>


</div>