config/routes.rb
Rails.application.routes.draw do

  get 'leader_boards/index'

  get('/', { to: 'welcome#about', as: 'home' })
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end


  resources :drills do
     member do
       get :delete
     end
   end

resources :drills do
  resources :answers
end

resources :attempted_drills


 resources :drill_groups do
   member do
     get :delete
   end
 end

 resources :leader_boards, only: :index
 resources :my_drills, only: [:index, :destroy] do
   member do
     get :delete
   end
 end

end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempted_drill.rb
class AttemptedDrill < ApplicationRecord
end

app/models/drill.rb
class Drill < ApplicationRecord
<<<<<<< HEAD
=======
  belongs_to :drill_group, :optional => true
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers

>>>>>>> a4a7eba20c25759ff95fdea51a308eb41151e36e
end

app/models/drill_group.rb
class DrillGroup < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_create :confirmation_token

  has_many :attempted_drills, dependent: :destroy
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX



  validates :first_name, :last_name, presence: true




  def full_name
  "#{first_name} #{last_name}".titleize.strip
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
  def confirmation_token
    if self.confirm_token.blank?
        self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def user_signed_in?
    if session[:user_id].present? && current_user.nil?
      session[:user_id] = nil
    end
    session[:user_id].present?
  end

  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  
  helper_method :current_user


  def authenticate_user!
    if !user_signed_in?
      redirect_to new_session_path, notice: 'Please sign in'
    end
  end


end

app/controllers/drill_groups_controller.rb
class DrillGroupsController < ApplicationController
  def index
    @drill_groups = DrillGroup.order("id")
  end

  def show
    # if redirect from new drill create =>
    #  if Drill.find_by(id: params[:id]) != nil
    #    @drill_group = Drill.find(params[:id]).drill_group
    #  else
    #    @drill_group = DrillGroup.find_by(id: params[:id])
    #  end
    @drill_group = DrillGroup.find_by(id: params[:id])
    @drills = @drill_group.drills

   end

  def new
    @drill_group = DrillGroup.new
  end

  def create
    @drill_group = DrillGroup.new(drill_group_params)

    if @drill_group.save
      flash[:notice] = "Drill Group created successfully"
      redirect_to(drill_groups_path)
    else
      flash[:error] = "Drill was not created"
      render("new")
    end
  end

  def edit
    @drill_group = DrillGroup.find(params[:id])
  end

  def update
    @drill_group = DrillGroup.find(params[:id])
    if @drill_group.update_attributes(drill_group_params)
      flash[:notice] = "Drill Group Updated"
      redirect_to(drill_groups_path)
    else
      render("edit")
    end
  end

  def delete
    @drill_group = DrillGroup.find(params[:id])
  end

  def destroy
    @drill_group = DrillGroup.find(params[:id])
    @drill_group.destroy

    flash[:notice] = "Drill Group destroyed!"
    redirect_to(drill_groups_path)
  end

  private
  def drill_group_params
    params.require(:drill_group).permit(:id,:drill_group_name, :difficulty)
  end



end

app/controllers/drills_controller.rb
class DrillsController < ApplicationController

  def index
    @drills = Drill.order("id")
  end

  def show
    if current_user === nil
      redirect_to new_user_path
    end
    @drill = Drill.find(params[:id])
    @answers = @drill.answers
    @attempted_drill = AttemptedDrill.new
    @drill_group = DrillGroup.find_by(id: params[:id])

  end

  def new
    @drill = Drill.new
    @drill.drill_group_id = params[:groupsId]
    4.times { @drill.answers.build}


  end

  def create
    @drill = Drill.new(drill_params)
    if @drill.save
      flash[:notice] = "Drill created successfully"
      redirect_to(drill_group_path(@drill.drill_group))
    else
      flash[:error] = "Drill was not created!"
      render("new")
    end
  end

  def edit
    @drill = Drill.find(params[:id])
  end

  def update
    @drill = Drill.find(params[:id])
    if @drill.update_attributes(drill_params)
      flash[:notice] = "Drill updated successfully"
      redirect_to(drills_path)
    else
      flash[:error] = "Drill was not updated!"
      render("edit")
    end
  end

  def delete
    @drill = Drill.find(params[:id])
  end

  def destroy
    @drill = Drill.find(params[:id])
    @drill.destroy

    flash[:notice] = "Drill destroyed successfully."
    redirect_to(drills_path)
  end

  private

  def drill_params
    params.require(:drill).permit(:title, :points, :drill_group_id, answers_attributes: [:body, :is_correct])
  end


end

app/controllers/my_drills_controller.rb
class MyDrillsController < ApplicationController

  def index

    @my_drills = {}
    @drill_groups = []
    my_att_drills = AttemptedDrill.where(user_id: current_user.id)
    my_att_drills.each do |drill|
      current_drill_group = DrillGroup.find_by_id(drill.drill_group_id)
      if !@my_drills.key?(current_drill_group.drill_group_name)
        group_total = my_att_drills.where(drill_group_id: current_drill_group.id)
        correct =  group_total.where(is_correct: true)
        score = (correct.count.to_f/group_total.count).round(2) * 100
        @my_drills[current_drill_group.drill_group_name] = score
        @drill_groups << current_drill_group
      end
    end
  end

  def delete
    @drill_group = DrillGroup.find(params[:id])
  end

  def destroy
    att_drills = AttemptedDrill.where(user_id: current_user.id).where(drill_group_id: params[:id])
    att_drills.destroy_all

    redirect_to(my_drills_path, notice: "Drills deleted!")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



  def new
  end


  def create

    user = User.find_by(email: params[:email])




    if user&.authenticate(params[:password])
      if user.email_confirmed
        session[:user_id] = user.id
        flash[:notice] = "Logged in Successfuly"
        redirect_to home_path
      else
        flash.now[:error] = "Please activate your account"
        render "new"
      end
    else
      flash.now[:alrt] = "Wrong email or password"
      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to home_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.score = 0;

    if @user.save
      UserMailer.registration_confirmation(@user).deliver

      redirect_to "/", notice: 'Thank you for singing up, please confirm your email address'
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end

  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      session[:user_id] = user.id
      flash[:notice] = "Logged in Successfuly"
      redirect_to home_path
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end



  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:username,
      :password, :password_confirmation)
  end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempted_drills_helper.rb
module AttemptedDrillsHelper
end

app/helpers/leader_boards_helper.rb
module LeaderBoardsHelper
end

app/helpers/my_drills_helper.rb
module MyDrillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BytesMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- navbar -->
    <div class="navbar-fixed">
      <nav class="z-depth-3">
        <div class="container">
          <div class="nav-wrapper">
            <%= link_to 'Bytes-Me!', home_path, class: "left brand-logo" %>
            <a href="#" data-activates="slide-out" class="right button-collapse">
                <i style="margin-top: 0px" class="fa fa-bars" aria-hidden="true"></i>
            </a>
            <ul class="right hide-on-med-and-down">
              <li><%= link_to 'Drill Groups', drill_groups_path	%> </li>
                <% if user_signed_in? %>
                <% if current_user.is_admin? %>
                <li><%= link_to "All Drills", drills_path%></li>
                <% end %>
                <li><%= link_to 'Leaderboard', leader_boards_path %> </li>
                <li class="hello-name">|</li>
                <li class="flex"><a href="#"><i class="material-icons">person</i><strong><%= current_user.full_name %></strong></a></li>
                <li><%= link_to 'Sign Out', sessions_path, method: :delete, data: {confirm: 'Logout?'} %></li>
                <% else %>
                  <li><%= link_to 'Log In', new_session_path %> </li>
                  <li><%= link_to 'Sign Up', new_user_path %> </li>
                <% end %>

            </ul>

          </div>
        </div>
      </nav>
    </div>
    <ul class="right side-nav teal-text" id="slide-out">
      <li><%= link_to 'Bytes-Me!', home_path, class: "brand-logo" %></li>
      <li><%= link_to 'Drill Groups', drill_groups_path	%> </li>
        <% if user_signed_in? %>
        <li><%= link_to 'Leaderboard', leader_boards_path %> </li>
          <li><%= link_to 'Sign Out', sessions_path, method: :delete, data: {confirm: 'Logout?'} %></li>
        <% else %>
          <li><%= link_to 'Log In', new_session_path %> </li>
          <li><%= link_to 'Sign Up', new_user_path %> </li>
        <% end %>
    </ul>
    <!-- navbar end -->

  <main class="bg-color">
    <%  unless current_page?(home_path)  %>
    <div class="box-page">

      <div class="container">
        <% if flash[:notice] %>
        <div class='alert alert-success'>
          <%= flash[:notice] %>
        </div>
        <% elsif flash[:alert] %>
        <div class='alert alert-danger'>
          <%= flash[:alert] %>
        </div>
        <% end %>

      <% end %>
        <%= yield %>
      </div>
    </div>

  </main>

  <!-- footer -->
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div style="align: center" class="col-lg-12 l4 offset-l2 s12">
            <a class="grey-text text-lighten-3" href="#!"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a class="grey-text text-lighten-3" href="#!"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            <a class="grey-text text-lighten-3" href="#!"><i class="fa fa-google" aria-hidden="true"></i></a>
            <a class="grey-text text-lighten-3" href="#!"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- footer end -->
  </body>
</html>